# Generated by Django 3.2 on 2023-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scholarship_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='close',
            new_name='expire',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='school',
            new_name='sponsor',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='details',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
